### ISSUE TITLE
cutscenes should use rough (nearest-neighbor) scaling like the in-game graphics do

### ISSUE THREAD

**Issue by ncrecc** [youkaicountry/yknytt#172]
this is especially obvious when a cutscene image *is* of in-game graphics:
![image](https://github.com/youkaicountry/yknytt/assets/11216597/f67a669b-6e76-4712-be82-0e84e1e83b3a)
(level: "Get focus" by canteven)

**Comment by up-left** [comment]
Can be done easily, but on the other hand, non-pixel-art pictures and fonts will become pixelated. Let me think about it later.

**Comment by up-left** [comment]
If someone has pros or cons to make cutscenes pixelated, feel free to write them here!

**Comment by up-left** [comment]
It's still ttf, because switching all controls to bitmap font is a very time consuming task. Maybe later somebody will find a better ttf font.
Also I made cutscenes pixelated (I think three people is enough), so there will be less reasons to turn smooth scaling off.
About KS+ custom fonts - I doubt that they will be made in the nearest future.
I tried to convert the image you posted to BMFont format (because Godot uses it), but it's also turned out to be a difficult task. So I set it aside.

**Comment by ncrecc** [comment]
the exact font that knytt stories's sign font is based on is SimSun (at 10px in the base game)
https://learn.microsoft.com/en-us/typography/font-list/simsun
![image](https://github.com/youkaicountry/yknytt/assets/11216597/8e5fcb58-3469-4031-ae53-10565a9c03b6)

**Comment by up-left** [comment]
Unfortunately, I can't use SimSun, it's 10MB in size and I doubt about licensing. Some lightweight font for pixel art should should suit better.

**Comment by up-left** [comment]
I can use it for signs if I (or somebody) manages to convert it to BMFont.
But for UI controls only TTF is suitable.

**Comment by up-left** [comment]
I changed the font for non-smooth scale mode. It has the same character set and looks okay. So if you have no objections, I can close this issue.
