### ISSUE TITLE
Maps not work

### ISSUE THREAD

**Issue by djsolidsnake86** [youkaicountry/yknytt#196]
there is no map when i press the button
for example in knytt stories ex there is a map for every level

**Comment by djsolidsnake86** [comment]
![knjump](https://github.com/youkaicountry/yknytt/assets/96209906/247fb28f-fb3e-47ac-b743-3058e9ab8ec9)

**Comment by djsolidsnake86** [comment]
> For a map to be available first you need the 'map' powerup.
> 
> You can add that powerup from within the console with the `map` command (`~` - tilde key or `pause`+`info` keys both trigger the console on/off).

this must be done for every level?

**Comment by djsolidsnake86** [comment]
maybe a option for enable it by default could be usefulf, is not a cheat

**Comment by djsolidsnake86** [comment]
> Some levels actually give you a map at the start or as a collectible powerup. There are some that 'reshape' the map and define unique colors for some areas.
> 
> It is up to a level developer to decide. If you want to override that - then I suppose it would be cheating. Still, the situation is not so simple, as most levels are just plain KS levels (without mods) where a map was not available at all, so couldn't be given.
> 
> Anyway, the authors are generally against adding too many options, so I would predict a hard time convincing them. You can still try - but I would suggest doing this as a feature request and not a bug, as this issue should be closed.

well knitt stories ex do the map by default, and really help this!

**Comment by djsolidsnake86** [comment]
exactly, only frozen mountain 2 show the map
all other levels no map, in ks ex the force map is implemented and work with all maps
hope this trick will be added
thanks

**Comment by fabzenfab** [comment]
Hello ;-)

why did you remove the colors in the map which indicated the different areas of the level ? it's very confusing now...

thanks

**Comment by fabzenfab** [comment]
Good morning,
I am not a programmer and perhaps you will find my question stupid... would it be possible to be able to mark certain boxes of the plan with an X for exemple. because in the big levels I never find where I have to come back. 
I don't know if this feature exists or not but it would be super useful ;-)
Thank you

**Comment by fabzenfab** [comment]
Ok I didn't see ;-)

**Comment by up-left** [comment]
I made "forced map" setting for the new version and enabled it by default. It's a controversial question, some levels with Format=2 will show garbage instead of map, orientation challenge will be lost, but on some cases it will be very useful. I can only guess which option is better. But pressing 'M' is a voluntary action, so I enabled map by default.

**Comment by fabzenfab** [comment]
thank you, the main thing is that the card is available. 
Afterwards, it is up to us to activate it or not depending on each level
great job !
