### ISSUE TITLE
6xbrz filter

### ISSUE THREAD

**Issue by djsolidsnake86** [youkaicountry/yknytt#197]
is possible add this video filter for have a better graphic less pixellated? thanks
6xbrz filter is used in snes9x emulator

**Comment by fabzenfab** [comment]
You mean to add some shaders ?

**Comment by djsolidsnake86** [comment]
nope, is a video filter for better graphics

**Comment by djsolidsnake86** [comment]
ah ok, sorry, so is a shader
yes the result is great on snes9x emulator with snes games that are pixellated, with the shaders not anymore pixellated :D

**Comment by fabzenfab** [comment]
interesting indeed, good idea !

**Comment by up-left** [comment]
Some shaders will be added to the new version, fortunately youkaicountry already did the main work. As for upscaling, Godot is restricted to its own shaders, so 6xbrz is not possible. But I found this one: https://godotshaders.com/shader/hq4x-shader-like-in-emulators/ . Only backgrounds will be upscaled, because upscaled Juni looks unhealthy =)
But I should warn, this option may be removed later, because it would be funny to play one or two levels with shaders, but usually players don't need them.

**Comment by fabzenfab** [comment]
Ok tanks ;-)
